# -*- coding: utf-8 -*-
"""Copy of Halloween.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18bDMjRJS-9QWJeCRrnHXqi--58rBQ78K
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from wordcloud import WordCloud
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# import plotly.express as px
# from plotly.subplots import make_subplots
# import plotly.graph_objects as go

df=pd.read_csv('candy-data.csv')
df=df.sort_values(by='winpercent', ascending=False)
df.head()

df.reset_index(drop=True)


df2=df.T

df2.columns=df2.iloc[0]



df2=df2.drop(index='competitorname')


df2.reset_index()

df2.index

df2.columns

df2.reset_index()

"""## Word Cloud"""

df.set_index('competitorname')['winpercent'].to_dict()

chocolate_popularity = df.set_index('competitorname')['winpercent'].to_dict()

# Create the WordCloud with size based on popularity
wordcloud = WordCloud(width=800, height=400, background_color='white',
                      max_font_size=60, min_font_size=10).generate_from_frequencies(chocolate_popularity)

# Display the WordCloud
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.title("Candy Competitors Sorted Based on their Win Percentage")
plt.show()

"""### Insight:
### Top 5 Halloween Candy Competitors Based On Their Winning Percentage:
1. ReeseOs Peanut Butter cup
2. ReeseOs Miniatures
3. Twix
4. Kit Kat
5. Snickers

## Correlationn Heatmap
"""

plt.figure(figsize=(12,6))
sns.heatmap(df.corr(), annot=True, cmap='RdYlGn')
plt.title('Correlation Between the Variables')
plt.show()

"""### Insight:
- Most of the candies that are fruity flavoured are bar candies and have less/no chocolate in them. These are less priced comparetively.
- If the candies are bar, then they are mostly not pluribus (one of many candies in a bag or box).
- Candies that are bar type and who tend to have more chocolate in them are little expensive and have high win percentage.
- Candies that have chocolate and nougat in them and are bar type are little expensive but have high win percentage.

## Bubble Chart
"""

import matplotlib.pyplot as plt
import matplotlib.cm as cm

# Create the bubble chart
plt.figure(figsize=(10, 6))

# Set colormap and normalize the 'winpercent' values for color mapping
colormap = cm.get_cmap('RdYlGn')
normalize = plt.Normalize(df['winpercent'].min(), df['winpercent'].max())

# Create a scatter plot with color mapping
sc = plt.scatter(
    x=df['sugarpercent'],
    y=df['pricepercent'],
    s=df['winpercent'] * 38,
    c=df['winpercent'],  # Use 'winpercent' for color mapping
    cmap=colormap,
    alpha=0.5,
)

# Add a colorbar to the chart to show the color scale
cbar = plt.colorbar(sc)
cbar.set_label('Win Percentage')

# Add labels and a title
plt.xlabel('sugarpercent')
plt.ylabel('pricepercent')
plt.title('Price Percentage vs Sugar Percentage (With Win Percentage)')

# Show the chart
plt.show()

"""### Insight:
- Candies that have more sugar content and are expensive tend to have more win percent.
"""

df2=df.head()
df2

df2=df2.T
df2

df2.columns=df2.iloc[0]
df2=df2.iloc[1:]
df2

df2.drop(columns=['competitorname'])

